#!/bin/bash

#setting values
k=""
u=false
#reading in arguments
while getopts ":k:u" opt; do
    case ${opt} in
        k)
            shift_value=$((OPTARG))
        ;;
        u)
            u=true

        ;;
    esac
done

#creating the pattern depending upon if u has been passed in
if [[ $u == true ]]; then
    #calling it arg2 since it is the second arguement called in tr
    arg2=$(./create_pattern -k $shift_value -u)
    arg1="[A-Z]"

else
    arg2=$(./create_pattern -k $shift_value)
    arg1="[a-z]"

fi
# echo $arg2

#reading lines of file
while IFS= read -r line; do
#running tr piping line of the file and passing in agruements
    translated=$(echo "$line" | tr "$arg1" "$arg2")
    echo "$translated"

done


