#!/bin/bash

#creating a string to pull from
letters="abcdefghijklmnopqrstuvwxyz"

#reading in arguments
while getopts ":k:u" opt; do
    case ${opt} in
        k)
            shift_value=$((OPTARG))
        ;;
        u)
        #changing string to uppercase
            letters="ABCDEFGHIJKLMNOPQRSTUVWXYZ"

        ;;
    esac
done





#grab the letter that corresponds to the shift value. print Z print A. wrap around to the value before the shift
echo "[${letters:shift_value:1}-${letters:25:1}${letters:0:1}-${letters:shift_value-1:1}]"




